### PR TITLE
Add more detailed steps to README

### PR DESCRIPTION
**Pull request by YuriiChere**

### CODE REVIEW

**Comment by YuriiChere** [comment]
I made update (in my previous PR) in ApplitoolsTutorial.csproj  i made  '<PackageReference Include="Eyes.Selenium" Version="*" />'. So now it should load latest version of package. I reinstall VS today and cloned repo and run it. As I see it use package Eyes.Selenium 2.23.4. So I think it isn't needed to update by Nuget. Maybe if you had already had old version of package... So if you want I can add this step

**Comment by rajaraodv** [comment]
OK, maybe add it as a troubleshooting step below the regular steps. Please
also add the screenshot that shows the exact SDK name.

Regards,
Raja
Head of Growth Marketing, Applitools <https://www.applitools.com> |
Director of Test Automation University <https://testautomationu.com>

**Comment by YuriiChere** [comment]
Ok, I will do it now

**Comment by YuriiChere** [comment]
Done

**Pull request merged**
